#cloud-config
%{ if length(extra_ssh_keys) > 0 }
ssh_authorized_keys:
%{ for ssh_key in extra_ssh_keys }
- ${ssh_key}
%{ endfor }
%{ endif }
bootcmd:
- apt-get update
- apt-get install -y apt-transport-https
apt:
  sources:
    docker:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable"
      keyid: 0EBFCD88
packages:
- [docker-ce, '5:19.03.5~3-0~ubuntu-bionic']
- jq
write_files:
# 1.1.1 - Configure default sysctl settings on all hosts
- path: /etc/sysctl.d/90-kubelet.conf
  owner: root:root
  permissions: '0644'
  content: |
    vm.overcommit_memory=1
    vm.panic_on_oom=0
    kernel.panic=10
    kernel.panic_on_oops=1
    kernel.keys.root_maxkeys=1000000
    kernel.keys.root_maxbytes=25000000
# 1.1.2 encription provider
- path: /opt/kubernetes/encryption.yaml
  owner: root:root
  permissions: '0600'
  content: |
    apiVersion: apiserver.config.k8s.io/v1
    kind: EncryptionConfiguration
    resources:
      - resources:
        - secrets
        providers:
        - aescbc:
            keys:
            - name: key1
              secret: QRCexFindur3dzS0P/UmHs5xA6sKu58RbtWOQFarfh4=
        - identity: {}
# 1.1.3 audit log
- path: /opt/kubernetes/audit.yaml
  owner: root:root
  permissions: '0600'
  content: |
    apiVersion: audit.k8s.io/v1beta1
    kind: Policy
    rules:
    - level: Metadata
# 1.1.4 event limit
- path: /opt/kubernetes/admission.yaml
  owner: root:root
  permissions: '0600'
  content: |
    apiVersion: apiserver.k8s.io/v1alpha1
    kind: AdmissionConfiguration
    plugins:
    - name: EventRateLimit
      path: /opt/kubernetes/event.yaml
- path: /opt/kubernetes/event.yaml
  owner: root:root
  permissions: '0600'
  content: |
    apiVersion: eventratelimit.admission.k8s.io/v1alpha1
    kind: Configuration
    limits:
    - type: Server
      qps: 5000
      burst: 20000
# 1.4.12 etcd user
groups:
  - etcd
users:
  - default
  - name: etcd
    gecos: Etcd user
    primary_group: etcd
    homedir: /var/lib/etcd

# 1.4.11 etcd data dir
runcmd:
  - sed -i -e 's/^Defaults\s\+requiretty/# \0/' /etc/sudoers
  - apt update
  - apt upgrade -y
  - usermod -G docker -a ubuntu
  - echo '{"log-driver":"json-file","log-opts":{"max-size":"10m","max-file":"6"}}' > /etc/docker/daemon.json
  - chmod 0700 /var/lib/etcd
  - sysctl -p /etc/sysctl.d/90-kubelet.conf
  - systemctl restart docker && systemctl enable docker